site_name: Chris' Tech Ramblings
site_description: A collection of thoughts and ideas on cloud, iot, software development, and other topics.
site_url: https://chrismryan.github.io
site_author: Chris Ryan

repo_name: 'GitHub'
repo_url: 'https://github.com/chmryan/chmryan.github.io'

docs_dir: 'docs'

copyright: "Copyright &copy; 2024 Chris M. Ryan"

extra_css:
  - stylesheets/extra.css

plugins:
  - blog
  - search
  - exclude:
      glob:
        - "**/include-*.md"
  - tags:
      enabled: true
      tags: true

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true

nav:
  - Blog:
      - blog/index.md
  - Projects: projects/index.md

theme:
  name: material
  icon:
    logo: material/cog-refresh-outline
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
